### PR TITLE
add react-16 support

### PR DESCRIPTION
**Pull request by modosc**
(the jsdom upgrade was necessary because some distant dependency doesn't work with node > `0.10` anymore and i couldn't get the tests to run)

### CODE REVIEW

**Comment by modosc** [comment]
thanks - any chance of getting a release for this to npm?

**Comment by boblauer** [comment]
yeah, sorry, i'm currently working on it.  having some trouble with the tests.  i'll let you know when it's published.

**Comment by modosc** [comment]
no problem - thanks for the quick response!

**Comment by boblauer** [comment]
published `@2.0.8`.  Thanks again for the pull!

**Pull request merged**
