### PR TITLE
Fix #6

### LINKED ISSUE #6: Deferred binding to window click causing strange testing effects
If a synchronous unit test is done that involves the component in any way, it will leave behind click events that will fire later. It's because the unmount is called before the deferred binding to the window.

The reason is that the binding to the window is deferred, but it should check that the component hasn't already unmounted before binding.

### PR DESCRIPTION
**Pull request by grassick**
I haven't actually tested this (sorry, one of those days), but it should prevent the unnecessary adding of a listener and it's really simple.

### CODE REVIEW

**Comment by grassick** [comment]
Ok, tested and works great!

**Comment by boblauer** [comment]
Thanks!

**Comment by grassick** [comment]
That's strange... I don't see these changes in master. Master still has the delaying binding issue in that setTimeout will run the next tick and leave a listener behind.

**Comment by boblauer** [comment]
see my comment here - https://github.com/boblauer/react-onclickout/issues/6#issuecomment-158823487

**Pull request merged**
